theme: minima
# site.url: https://mickfuzz.github.io/phd4/
header_pages:
 - index.md
 - blogs.md
#for reference how to categorise


title: MickFuzz Blog and Writing
description: A test site for personal writing

url: https://mickfuzz.github.io
#url: https://localhost


baseurl: /mickfuzzblog
imgurl: https://github.com/mickfuzz/mickfuzzblog/blob/master/
show_excerpts: true
